title = "Sheffood – Sheffield's Food Partnership"
baseurl = "/"
languageCode = "en-gb"
languageLang = "en"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -110

[[menu.main]]
identifier = "forum"
name = "Forum"
url = "https://forum.sheffood.org.uk/categories"
weight = 40