backend:
  name: git-gateway
  branch: sheffood-initial # Branch to update (optional; defaults to master)

# Enables publishing workflow. Comment this line out to publish immediately
# publish_mode: editorial_workflow

media_folder: "site/static/images"
public_folder: "/images"

collections:
  - name: "config"
    label: "Config"
    files:
      - label: "Site"
        name: "site"
        file: "site/config.toml"
        fields:
           # - {label: Title, name: title, widget: string}
           # - {label: Intro, name: intro, widget: markdown}
           - label: Menu
             name: menu
             widget: object
             fields:
              - label: Navbar
                name: main
                widget: list
                fields:
                  - {label: Identifier, name: identifier, widget: string}
                  - {label: Name, name: name, widget: string}
                  - {label: URL, name: url, widget: string}
                  - {label: Weight, name: weight, widget: number}

  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "site/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}